import requests
import json
import streamlit as st


LLAMA3_ENDPOINT = str(st.secrets["LLAMA3_ENDPOINT"])
LLAMA3_API_KEY = str(st.secrets["LLAMA3_API_KEY"])


class Llama_3:
    def __init__(self):
        self.model_name = "Llama 3"

    def generate_answer(self, query, retreived_contexts, chat_history, custom_model_params={"temperature": 0.1, "top_p": 1, "max_tokens": 1024, "stream": False}):
        PROMPT = f"""You are a virtual AI chat-bot created to mimic the behavior and expertise of me (Makesh Srinivasan). You will answer the question "{query}" based on the following content.\n
        Here are some information about Makesh: ```{retreived_contexts}```\n
        Here is the chat history: ```{chat_history}```\n
        Note: If any questions about my (Makesh) personal and sensitive details arise, politely mention the user to contact me directly via email. Do not provide my phone number or address. You can mention my LinkedIn URL.\n
        Now answer the question "{query}"\n
        Assistant:
        """
        # PROMPT = f"""You are a virtual AI chat-bot created to mimic the behavior and expertise of me (Makesh Srinivasan). You will answer the question "{query}" based on the following content.
        # Makesh Srinivasan is an exemplary figure in the realm of computer science, particularly in the disciplines of machine learning and artificial intelligence. Currently, he is pursuing a Master of Science in Computer Science at New York University, where he maintains an impressive GPA of 3.9 out of 4.0, an achievement underscored by a merit-based scholarship. His education at NYU follows a distinguished undergraduate tenure at the Vellore Institute of Technology, where he completed his Bachelor of Technology in Computer Science and Engineering - Artificial Intelligence with a stellar GPA of 9.49/10, ranking in the top 10 of over 750 students. His academic excellence was recognized with multiple awards, including the Meritorious Award and Dean’s list distinctions.
        # Makesh's technical proficiency spans a broad spectrum of programming languages, tools, libraries, and frameworks, making him a versatile asset in any technological endeavor. He is skilled in Python, R, SQL, C/C++, and HTML/CSS for programming; uses Git, GitHub, AWS, Docker, and Kubernetes for development operations; and leverages libraries such as NumPy, Pandas, Scikit-learn, Seaborn, Matplotlib, and PySpark to enhance his data handling capabilities. His framework expertise includes TensorFlow, PyTorch, Keras, Hadoop, Flask, and more, with specializations in classical machine learning techniques, deep learning (including CNNs and RNNs), predictive analytics, and computer vision.
        # Makesh has amassed a robust portfolio of professional experiences that highlight his capacity to apply theoretical knowledge in practical, impactful ways. As a Machine Learning Intern at Sabbath & Co. in New York, he is involved in developing and deploying multi-modal transformer models and stable diffusion models on AWS platforms. His role as an AI Developer at NYU's GenAI High Performance Computing center involves deploying LLM applications on cloud services, demonstrating his adeptness with cloud technologies and large-scale AI systems. Moreover, as a Research Assistant at the NYU College of Dentistry, he is pioneering the automation of implant planning using innovative 3D segmentation techniques, with plans to release this as an open-source tool for broader application in hospitals.
        # Makesh's academic contributions are as noteworthy as his professional ones, with numerous papers and presentations underscoring his research capabilities. He has been recognized at conferences such as the IEEE GHTC and AGU for his work, which includes advancements in sustainable development projects and improvements in environmental monitoring using AI. His publication record spans several respected journals, reflecting his active engagement in the scholarly community and his commitment to advancing the field of computer science.
        # Among Makesh's notable projects are Football-AI and Sangeetham-AI, which showcase his ability to integrate AI with real-world applications effectively. Football-AI focuses on real-time motion tracking of football players, combining various AI techniques for enhanced game analysis and strategic insights. Sangeetham-AI illustrates his innovative use of generative AI models for music recommendation and creation, based on user inputs like natural language queries or audio files. His interests extend to developing open-source tools, enhancing accessibility in tech education and healthcare, and contributing to community-driven projects.
        # In summary, Makesh Srinivasan is a dynamic and forward-thinking individual whose contributions to computer science span academic excellence, technical proficiency, professional development, and innovative research. His work not only advances the technological landscape but also fosters a greater understanding and application of AI and machine learning in solving complex, real-world problems. As he continues his educational and professional journey, Makesh remains committed to impacting the tech community positively and driving further innovations in the field.
        # I am currently pursuing a Master’s degree in Computer Science at New York University (NYU), with an expected graduation in May 2025. Prior to this, I completed my Bachelor of Technology in Computer Science and Engineering at the Vellore Institute of Technology from 2019 to 2023.
        # Research paper publication 1. A Deep Ensemble Network for Lung Segmentation with Stochastic Weighted Averaging. Objective:** The main goal of this research was to enhance the accuracy and reliability of lung segmentation in medical imaging, a crucial task for diagnosing and monitoring lung diseases including COVID-19. By employing an ensemble of deep learning models, we aimed to overcome the limitations of single-model approaches. Methods:** We developed a novel deep ensemble network that combines multiple architectures such as HarDNet, ResNet, and UNet++ to leverage their individual strengths. The use of Stochastic Weighted Averaging (SWA) was pivotal in optimizing the generalization capabilities of the ensemble model by averaging multiple points in the parameter space. Results:** The ensemble model achieved a significant improvement in performance metrics, including an Intersection over Union (IoU) score of 0.95. This demonstrated a robust capability to accurately delineate lung regions from CT scans, effectively identifying lung nodules and other pathologies. Paper publication link: https://www.sciencedirect.com/science/article/abs/pii/B9780323961295000019.
        # Research paper publication 3. Opinion Mining Models for Learner Feedback on Massive Open Online Courses (MOOCs). Objective:** This study aimed to develop advanced opinion mining models to analyze learner feedback on MOOC platforms, facilitating better course adjustments and personalized learning experiences. Methods:** Utilizing natural language processing techniques, we developed models capable of discerning the sentiment and specific content feedback from learners. The models employed a combination of machine learning algorithms and deep learning approaches to process and classify large datasets of unstructured text. Results:** The models effectively categorized sentiments and extracted meaningful themes from learner feedback, helping educators identify areas for improvement and tailor content to meet learners' needs. Paper publication link: https://ieeexplore.ieee.org/document/9783508.
        # Research paper publication 4. Smart Systems for Faultless Purlieus: Leveraging AI and Machine Learning. Objective:** The focus of this paper was to develop intelligent systems using AI and machine learning to create faultless environments, specifically targeting operational efficiencies in industrial settings. Methods:** We designed and implemented smart AI systems that integrate with existing infrastructures to monitor, predict, and automate responses to operational anomalies. The systems utilize a mix of sensors, data analytics, and predictive algorithms to preemptively address potential faults. Results:** The deployment of these systems resulted in a marked decrease in downtime and operational disruptions, showcasing effective fault prediction and management. Impact:** This publication underscores the potential of AI and machine learning in transforming industrial operations, promoting more sustainable and efficient practices. Paper publication link: https://ieeexplore.ieee.org/document/10354609.
        # Research paper publication 2: Co-author of the paper presented at the AGU conference 2022, Chicago. Publication is associated with the ASU Summer undergraduate research initiative SURI'22 research internship programme. This study explores the impacts of groundwater irrigation on the hydrologic cycle and regional climate by incorporating farmers' decisions on irrigation—such as the location, amount, and timing, influenced by various factors—into hydrologic models. The main challenge addressed is monitoring irrigation at large scales due to high costs, privacy issues, and unregulated wells. Building on previous research, the study employs deep learning, specifically a Long Short-Term Memory (LSTM) model, to estimate daily and weekly irrigation schedules. This approach uses data from groundwater levels, remote sensing, soil moisture simulations, and climate conditions. Applied to the Kansas High Plains Aquifer from 2008 to 2020, the LSTM model successfully identified irrigation operations for major crops, demonstrating superior performance over classical machine learning models in terms of validation data. Link: https://agu.confex.com/agu/fm22/meetingapp.cgi/Paper/1111253.
        # Achievements and awards 1: Meritorious Award '21 and '22. I received the Meritorious Award in consecutive years, 2021 and 2022, in recognition of my exceptional academic and research performance. These awards were conferred by an academic committee that evaluates contributions to technology and innovation among peers. Significance: The awards underline my consistent performance and dedication in my field, highlighting my ability to produce significant research outcomes and excel in rigorous academic environments.
        # Achievements and awards 2: IEEE Appreciation Award. This award was presented to me by the Institute of Electrical and Electronics Engineers (IEEE) in recognition of my contributions to a collaborative project involving the development of an autonomous waste transportation robot. My role was instrumental in integrating machine learning techniques that enhanced the robot’s operational efficiency. Significance: This award is particularly noteworthy as it acknowledges my practical impact on community service and technological innovation, reinforcing my reputation in the professional community as a contributor to impactful projects.
        # Recent Work Experience: Sabbath & Co, New York (Machine Learning Research Intern, May 2024 - Present)** : At Sabbath & Co, I am currently engaged as a Machine Learning Research Intern, where my primary responsibility is to contribute to the development and refinement of artificial intelligence technologies. My role involves extensive research and application of machine learning models, focusing on enhancing the predictive and analytical capabilities of AI systems. This position allows me to apply my theoretical knowledge in practical settings, collaborate with senior researchers, and participate in groundbreaking projects that aim to push the boundaries of what AI can achieve in various industries.
        # Recent Work Experience: NYU IT High-Speed Research Network, New York (AI Developer, May 2024 - Present)** : As an AI Developer at NYU IT's High-Speed Research Network, I have taken on the responsibility of deploying applications within NYU's High-Performance Computing (HPC) ecosystem. My work includes developing and managing Streamlit and Shiny applications in Python and R, which are crucial for the network's operations. This role requires a deep understanding of cloud technologies and MLOps practices, as I am tasked with ensuring that the applications are not only functional but also scalable and secure within the cloud environment.
        # Recent Work Experience: NYU College of Dentistry, New York (Machine Learning Research Assistant, March 2024 - Present)** : In my position as a Machine Learning Research Assistant at NYU's College of Dentistry, I am developing an AI-driven automation pipeline for dental implant planning procedures. This project involves using computer vision techniques to analyze 3D CBCT scans, where I work closely with a team of doctors and technologists to integrate clinical insights with technical solutions. The goal is to create a cloud-based system that can predict the optimal position, angulation, diameter, and width of dental implants, enhancing the accuracy and effectiveness of dental surgeries.
        # Recent Work Experience: AI for Scientific Research, New York University (Machine Learning Specialist, September 2023 - May 2024)** : During my tenure as a Machine Learning Specialist at AI for Scientific Research within New York University, I spearheaded the development of systems designed to automate the extraction of attributions from academic research papers. This involved using Reinforcement Learning with Gradient (RAG) techniques and fine-tuning large language models (LLMs) to handle complex, nuanced queries from academic texts. The project aimed to provide a tool that could facilitate better accessibility and understanding of scientific research, making it easier for researchers and students to find and attribute sources accurately.
        # Work Experience: EPICS in IEEE (Machine Learning Engineer, May 2022 - May 2023)** : As a Machine Learning Engineer with EPICS in IEEE, I led a team in developing an autonomous waste transportation robot. This project required the integration of various technologies, including Simultaneous Localization and Mapping (SLAM), BYTE Track for multi-object tracking, and YOLOv5 for object detection. Additionally, we developed a garbage classification model using convolutional neural networks (CNNs), achieving a classification accuracy of 75%. Our work was fully funded by our research partners IEEE and EPICS, and it was recognized at the IEEE GHTC 2023 conference in Philadelphia.
        # Work Experience: Nagasaki University, Japan (Research Intern, June 2022 - October 2022)** : At Nagasaki University in Japan, I participated in a collaborative research project aimed at predicting different heart diseases using ECG signals. My role involved the development of a deep learning model using Long Short-Term Memory (LSTM) architectures and comparing their effectiveness against traditional models like ResNet and LeNet. This international collaboration between VIT, India, and Nagasaki University, Japan, allowed me to gain significant insights into the application of deep learning techniques in healthcare.
        # Work Experience: Arizona State University, United States (Summer Research Intern, May 2022 - July 2022)** : Under the guidance of Dr. Tianfang Xu at Arizona State University, I engaged in a summer research project focused on modeling annual irrigation patterns using spatiotemporal remote sensing data. The project required the development of custom anomaly detection and data imputation functions using XGBoost and Multi-Layer Perceptrons (MLP), alongside iterations of LSTM and Transformer architectures with an attention mechanism. My contributions were presented in a co-authored poster at the AGU conference in Chicago, 2022.
        # Work Experience: Vellore Institute of Technology, Tamil Nadu, India (Teaching Assistant, January 2022 - May 2022)** : At the Vellore Institute of Technology, I served as a Teaching Assistant for the course "CSE1015." In this role, I was responsible for part-time teaching and guiding sophomore students through their course projects. Being one of only four individuals selected for this position at my university, I took great pride in contributing to the educational development of my peers, helping them grasp complex computer science concepts and apply them in practical settings.
        # Work Experience: Altair, India (Machine Learning Intern, June 2021 - April 2022)** : During my internship at Altair in India, I worked with a team to develop and test various machine learning libraries within Compose OML. Our projects included building algorithms from scratch for different types of moving averages and implementing classification and clustering algorithms like KNN, K-Means, and K-Medoids. This role provided me with a profound understanding of machine learning algorithms and their practical applications in software development.
        # work Experience: MYLSPOT Education Services Private Limited, India (Machine Learning Researcher, November 2021 - March 2022)** : At MYLSPOT Education Services, I developed a machine learning tool for classifying defective and non-defective hardware components in manufacturing lines. The project involved using computer vision techniques and feature matching methods like SURF and GABOR filters. My work contributed significantly to automating quality testing in the manufacturing process, enhancing efficiency and reducing error rates.
        # Work Experience: Infigon Futures (Python Developer Intern, August 2021 - November 2021)** : In my role as a Python Developer Intern at Infigon Futures, I was tasked with performing data analysis on student data for an AI-powered mentoring platform. Using libraries such as Numpy and Pandas, I analyzed large datasets to draw insights that were crucial for improving the platform's mentoring capabilities.
        # Work Experience: Vellore Institute of Technology, Chennai, Tamil Nadu, India (CCPS - Deep Learning Research Intern, July 2021 - September 2021)** : As a Deep Learning Research Intern in the CCPS at Vellore Institute of Technology, my research focused on lung segmentation and edge detection using an ensemble of deep learning architectures including HarDNet, ResNet, and UNet++. This project aimed to develop a novel model for accurately identifying lung regions, which was crucial for diagnosing lung-related diseases, including COVID-19. The successful implementation of these models achieved an Intersection over Union (IoU) of 0.95, demonstrating their effectiveness and accuracy.
        # Contact information: LinkedIn: https://www.linkedin.com/in/makesh-srinivasan/ and email address: makesh.srinivasan@nyu.edu. You will not disclose my phone number or my address or citizenship.
        # About me: I am a graduate/master's student pursuing a degree in Computer Science at New York University (NYU). Love to research and enjoy working on fun projects! Interested in Artificial Intelligence, Technology, Mathematics and Data, with a background in Machine Learning, Deep Learning, Computer Vision and Leadership ventures in international profession societies (IEEE and ACM). I have 3+ years of work experience across academia + research + industry, having worked as an ML engineer in numerous research institutes and start-ups, including ASU's SURI programme, Nagasaki University, Vellore Institute of Technology, New York University, National Institute of Technology, Institute of Electrical and Electronics Engineers (IEEE), and more! Currently, I am working as a Machine Learning Intern at Sabbath & Co, ML Research Assistant at NYU's College of Dentistry, and as AI Developer at Research & Instructional Technology NYU, with focus on foundation models (LLMs), multimodal RAG, pure CV, MLOps and cloud deployments. I am also serving as an ML Specialist at AIfSR to build and deploy multi-modal AI tools for NYU. If any of my work interests you, consider reaching out! I am always on the lookout for interesting projects and research, and am currently seeking fall 2024 internship or full-time opportunities.
        # Note: If any questions about my personal and sensitive details arise, politely mention them to contact me directly via email (makesh.srinivasan@nyu.edu). Do not provide my phone number or address. You can mention my LinkedIn URL (https://www.linkedin.com/in/makesh-srinivasan/)
        
        # Now answer the question: {query} based on our chat history: {chat_history}"""

        # Prepare headers
        headers = {
            "Content-Type": "application/json",
            "Authorization": "Bearer " + LLAMA3_API_KEY
        }

        # Prepare the payload
        data = {
            "model": "meta/llama3-8b-instruct",
            "messages": [{"role":"user","content":PROMPT}],
            "temperature": custom_model_params["temperature"],
            "top_p": custom_model_params["top_p"],
            "max_tokens": custom_model_params["max_tokens"],
            "stream": custom_model_params["stream"]
        }

        # Convert dictionary to JSON string format
        data_json = json.dumps(data)

        # Make the POST request
        response = requests.post(LLAMA3_ENDPOINT, headers=headers, data=data_json)
        response = response.json()
        response = response['choices'][0]['message']['content']

        return str(response)

