PINECONE_API_KEY="7d26760d-8c1c-435f-84f0-3039836b51d0"
LLAMA3_ENDPOINT="https://integrate.api.nvidia.com/v1/chat/completions"
LLAMA3_API_KEY="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"